config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:'pages#home'

  post 'pages/follow/:id', to: 'pages#relate', as: :follow
  delete 'pages/unfollow/:poster_id', to: 'pages#unrelate', as: :unfollow

  get 'pages/profile_user/:id', to: 'pages#profile_user', as: :profile_user
  # resources :profile, except: [:new, :index]

  resources :tweets, except: [:index, :new] do
    resources :tags
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :subscriber, class_name: "User"
  belongs_to :poster, class_name: "User"

  validate :disallow_subscribe_to_self
  def disallow_subscribe_to_self
    if subscriber_id == poster_id
      errors.add(:poster_id, 'cannot follow yourself')
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags, dependent: :destroy
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  has_many :tweet_tags, dependent: :destroy
  has_many :tags, through: :tweet_tags

  belongs_to :user

  validates :tweet, presence: true

end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :rememberable, :trackable
  devise :database_authenticatable, :registerable, :recoverable, :validatable

  has_one :profile, dependent: :destroy

  has_many :tweets, dependent: :destroy

  has_many :subscriber_users, class_name: "Relation", foreign_key: :poster_id, dependent: :destroy
  has_many :subscribers, through: :subscriber_users

  has_many :poster_users, class_name: "Relation", foreign_key: :subscriber_id
  has_many :posters, through: :poster_users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

    def relate
      @follow = Relation.new(subscriber_id: current_user.id, poster_id: params[:id])
      if @follow.save
        flash[:notice] = "Now following."
        redirect_to root_path
      else
        flash[:error] = "Unable to follow user."
        redirect_to root_path
      end
    end

    def unrelate
      @follow = Relation.find_by(subscriber_id: current_user.id, poster_id: params[:poster_id])
      if @follow != nil && @follow.destroy
        flash[:notice] = "Unfollowed."
        redirect_to root_path
      else
        flash[:alert] = "Unable to unfollow user."
        redirect_to root_path
      end
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @tweets = current_user.tweets.order(created_at: :desc).select { |tweet| tweet.id != nil }
    @users = User.all.select { |user| user != current_user && user.id != nil }
  end

  def profile_user
    @user = User.find(params[:id])
    @tweets = @user.tweets.select { |tweet| tweet.id != nil }
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag = Tag.all
  end
  def new
    @tweet = Tweet.tags.find(params[:tweet_id])
  end

  def create
    @tweet = Tweet.tags.find(params[:tweet_id])
    @tag = @tweet.tags.new(tag_params)
    if @tag.save
      redirect_to root_path
    else
      render :new
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to root_path
  end

private
  def tag_params
    params.require(:tag).permit(:tag)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      flash.now[:alert] = "Tweet is empty."
    end
  end

  def show
    # show any tweet based on id, regardless of whether user is author
    @tweet = current_user.tweets.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

private

  def tweet_params
    params.require(:tweet).permit(:tweet)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <title>Twitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Exo+2">

  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.username %></strong>.
          <!-- <%= link_to 'Edit account settings', edit_user_registration_path, :class => 'navbar-link' %> | -->
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </nav>
    <% flash.each do |key, value| %>
      <p><%= "#{key}: #{value}" %></p>
    <% end %>
      <!-- <p class="notice"><%= notice %></p> -->
      <!-- <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </body>
</html>

app/views/pages/_tweets.html.erb
<div id="tweets-index">
  <% @tweets.each do |tweet| %>
    <div class="card">
      <div class="card-body">
        <%= tweet.created_at.strftime("%d %b, %H:%M") %>
        <br>
        <%= tweet.tweet[0,150] %>
        &nbsp
        <%= link_to 'Edit', edit_tweet_path(tweet) %>
        <%= link_to 'Delete', tweet_path(tweet), method: :delete, data: { confirm: 'Sure?' } %>
      </div>
    </div>
    <br>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Welcome!</h1>

<div class="container-fluid">
  <div class="row align-items-center" style="height: 60%;">
    <div class="col">
      <div class="row">

        <div class="col-sm-1" id="home-left">
        </div>

        <div class="col-sm-5" id="home-center">
          <div class="card">
            <div class="card-body">
              <%= simple_form_for current_user.tweets.build, url: tweets_path(current_user), method: :post, remote: true do |f| %>
                <%= f.input :tweet, required: false, label: false, placeholder: "What's Happening?" %>
                <br>
                <%= f.button :submit %>
              <% end %>
            </div>
          </div>
          <br>
          <%= render partial: 'tweets' %>
        </div>

        <div class="col-sm-2" id="home-right">
          <div class="row">
            <div class="card">
              <div class="card-body">
                <%= current_user.posters.count %> following
                <br>
                <%= current_user.subscribers.count %> followers
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            My followers
            <br>
            Users I follow
          </div>
          <br>
          <div class="row">
            <h3>Suggested Users to Follow</h3>
            <ul>
              <% @users.each do |user| %>
              <li>
                <%= link_to user.username, profile_user_path(user) %>
                &nbsp
                <%= link_to "follow", follow_path(user), method: :post if Relation.find_by(subscriber_id: current_user.id, poster_id: user.id) == nil %>
                <%= link_to "UnF", unfollow_path(user), method: :delete if Relation.find_by(subscriber_id: current_user.id, poster_id: user.id) != nil %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<h1>This is <strong><%= @user.username %></strong>'s Page</h1>
<%= link_to "Back to My Feed", root_path %>

<div class="container-fluid">
  <div class="row align-items-center" style="height: 60%;">
    <div class="col">
      <div class="row">

        <div class="col-sm-2" id="profile-left">

        </div>

        <div class="col-sm-5" id="profile-center">
          <% @tweets.each do |tweet| %>
            <div class="card">
              <div class="card-body">
                <%= tweet.created_at.strftime("%d %b, %H:%M") %>
                <br>
                <%= tweet.tweet %>
              </div>
            </div>
            <br>
          <% end %>
        </div>

        <div class="col-sm-2" id="profile-right">

        </div>

      </div>
    </div>
  </div>
</div>

app/views/pages/profile_user.html.erb
<h1>This is <strong><%= @user.username %></strong>'s Page</h1>
<%= link_to "Back to My Feed", root_path %>

<div class="container-fluid">
  <div class="row align-items-center" style="height: 60%;">
    <div class="col">
      <div class="row">

        <div class="col-sm-2" id="profile-left">

        </div>

        <div class="col-sm-5" id="profile-center">
          <% @tweets.each do |tweet| %>
            <div class="card">
              <div class="card-body">
                <%= tweet.created_at.strftime("%d %b, %H:%M") %>
                <br>
                <%= tweet.tweet %>
              </div>
            </div>
            <br>
          <% end %>
        </div>

        <div class="col-sm-2" id="profile-right">

        </div>

      </div>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= simple_form_for @tweet, url: tweet_path(@tweet), method: :put do |f| %>
<%= f.input :tweet %>
<%= f.button :submit, "Update Tweet" %>
<% end %>